In [1]:
import numpy as np
import pandas as pd

In [11]:
mc = np.random.randint(10, size=(10, 10))
mc += 1
print(mc)


[[ 8  7  5  1  4  8  3  2  2  3]
 [ 9 10  6  6  2  3  4  1  2  4]
 [ 6  2  6  1  1 10  5  5  6  8]
 [ 3  4  9  7  2  2  8 10  9  4]
 [ 6  3  5  6  8  7  6  9 10  4]
 [ 8 10  2  3  4  1  9  2  1  7]
 [ 5  2  3  7  5  5  1  4  6  9]
 [ 4  8  4 10  1  3 10  3  9  1]
 [ 4  9  2  8  1  9  3  7  3  8]
 [ 5  5  5  2  2  4  8  8  8  7]]


In [4]:
def precison(mc,r):
    
    m = mc[r,r]
    #print('m= ',m)
    #print('m= ',mc[r,1])
    sumMC = np.sum(mc[r,:])
    #print(sumMC)
    pre = m/sumMC
    return pre

In [5]:
def recall(mc,c):
        
    m = mc[c,c]
    #print('m= ',m)
    #print('m= ',mc[r,1])
    sumMC = np.sum(mc[:,c])
    #print('rec sum:',sumMC)
    rec = m/sumMC
    #print('rec: ',rec)
    return rec

In [12]:
f_score = []
for i in range(10):
    pre = precison(mc,i)
    #print('precision: ', pre)
    rec = recall(mc,i)
    #print('recall: ',rec)
    ppr = pre*rec
    #print(ppr)
    pmr = pre+rec
    #print(pmr)
    f = 2*ppr/pmr
    print(f)
    f_score = np.append(f_score,f)
    
print(f_score)

0.15841584158415842
0.18691588785046728
0.12371134020618556
0.12844036697247707
0.1702127659574468
0.0202020202020202
0.01923076923076923
0.05769230769230769
0.05454545454545454
0.12844036697247707
[0.15841584 0.18691589 0.12371134 0.12844037 0.17021277 0.02020202
 0.01923077 0.05769231 0.05454545 0.12844037]


In [54]:
avgFscore = (1/10)*np.sum(f_score)
print(avgFscore)
save_metricas_dl(avgFscore,f_score)

0.10478071212137641


In [53]:
def save_metricas_dl(avgF, fscore):   
    fscore = np.append(fscore,avgF)
    archivo = open('estima_dl.csv', 'w')

    [archivo.write(f'{fscore[i]},') for i in range(len(fscore)) ]

    
    archivo.close()

In [111]:
data= np.load('x.npy')
print(data.shape)
df= pd.DataFrame(data=data)
#df

data2= np.load('y.npy')
#data2.shape
df2= pd.DataFrame(data=data2)
#df2


(10, 400)


In [113]:
df2

0         1         2         3         4         5         6    \
0  0.000213  0.000217  0.000207  0.000185  0.000364  0.000398  0.000288   
1  0.000207  0.000211  0.000200  0.000180  0.000353  0.000386  0.000279   
2  0.000196  0.000200  0.000190  0.000170  0.000334  0.000366  0.000265   
3  0.000193  0.000197  0.000187  0.000168  0.000330  0.000361  0.000261   
4  0.000204  0.000208  0.000198  0.000177  0.000348  0.000381  0.000276   
5  0.000208  0.000212  0.000202  0.000181  0.000355  0.000388  0.000281   
6  0.000218  0.000222  0.000211  0.000190  0.000372  0.000407  0.000295   
7  0.000212  0.000217  0.000206  0.000185  0.000363  0.000397  0.000287   
8  0.000198  0.000201  0.000192  0.000172  0.000337  0.000369  0.000267   
9  0.000215  0.000219  0.000209  0.000187  0.000367  0.000402  0.000291   

        7         8         9    ...       390       391       392       393  \
0  0.000313  0.000359  0.000235  ...  0.000233  0.000196  0.000282  0.000201   
1  0.000303  0.000348  0.000228  ...  0.000226  0.000190  0.000273  0.000195   
2  0.000287  0.000330  0.000216  ...  0.000214  0.000180  0.000259  0.000185   
3  0.000283  0.000325  0.000213  ...  0.000211  0.000177  0.000255  0.000182   
4  0.000299  0.000344  0.000225  ...  0.000223  0.000187  0.000270  0.000193   
5  0.000305  0.000350  0.000229  ...  0.000228  0.000191  0.000275  0.000196   
6  0.000320  0.000367  0.000241  ...  0.000239  0.000200  0.000288  0.000206   
7  0.000312  0.000358  0.000234  ...  0.000233  0.000195  0.000281  0.000200   
8  0.000290  0.000333  0.000218  ...  0.000216  0.000181  0.000261  0.000186   
9  0.000316  0.000363  0.000238  ...  0.000236  0.000197  0.000285  0.000203   

        394       395       396       397       398       399  
0  0.000307  0.000256  0.000158  0.000285  0.000343  0.000303  
1  0.000297  0.000248  0.000153  0.000276  0.000333  0.000294  
2  0.000282  0.000235  0.000145  0.000262  0.000315  0.000278  
3  0.000278  0.000232  0.000143  0.000258  0.000311  0.000275  
4  0.000294  0.000245  0.000151  0.000273  0.000329  0.000290  
5  0.000299  0.000250  0.000154  0.000278  0.000334  0.000296  
6  0.000314  0.000262  0.000162  0.000292  0.000351  0.000310  
7  0.000306  0.000255  0.000157  0.000284  0.000342  0.000302  
8  0.000284  0.000237  0.000146  0.000264  0.000318  0.000281  
9  0.000310  0.000259  0.000160  0.000288  0.000347  0.000306  

[10 rows x 400 columns]

In [100]:
def norm(df):
    a = 0.01
    b = 0.99
    df_norm = pd.DataFrame()
    
    for col in df:
        min_ = df[col].min()
        max_ = df[col].max()

        df_norm[col] = (df[col] - min_) * (b - a) / (max_ - min_) + a
    
    x = df_norm
    x = x.T
    return (x.to_numpy())

In [104]:
sumatoria = []
for i in range(10):
    sumatoria = np.append(sumatoria, np.sum(data[i][:]))
    
f = pd.DataFrame(data = sumatoria)
f
x=norm(f)


sumatoria2 = []
for i in range(10):
    sumatoria2 = np.append(sumatoria2, np.sum(data2[i][:]))

f2 = pd.DataFrame(data = sumatoria2)
y=norm(f2)
y


array([[0.80132565, 0.54342589, 0.11483054, 0.01      , 0.44346538,
        0.58799275, 0.99      , 0.77132565, 0.18843668, 0.88419318]])

In [110]:
y

array([[0.80132565, 0.54342589, 0.11483054, 0.01      , 0.44346538,
        0.58799275, 0.99      , 0.77132565, 0.18843668, 0.88419318]])